alert('Кто разработал язык программирования JavaScript? = Брендан Эйх')
alert('За сколько дней был разработан JavaScript? = 10 дней')
alert('В каком году появился JavaScript? = в сентябре 1995 года')
alert('JavaScript - это то же самое, что и Java? = JavaScript это не Java')
alert('Как называется спецификация JavaScript? = ECMAScript')